project:
  type: website
  output-dir: docs/

website:
  navbar:
    left:
      - text: "Home"
        file: index.qmd
      - sidebar:qqdataproj
      - sidebar:appliedproj
      - file: about.qmd
  sidebar:
    - id: qqdataproj
      title: "QQ Data Project"
      style: "docked"
      background: light
      contents:
        - pages_of_site/qq_data_project/proj_bckgd/introduction.qmd
        - pages_of_site/qq_data_project/proj_bckgd/methods.qmd
        - pages_of_site/qq_data_project/analysis/data_cleaning/sample_data_cleaning_page.qmd
        - pages_of_site/qq_data_project/analysis/data_analysis/sample_analysis_page.qmd
        - pages_of_site/qq_data_project/proj_outcomes/results/results.qmd
        - pages_of_site/qq_data_project/proj_outcomes/discussion/discussion.qmd
    - id: appliedproj
      title: "Applied Project"
      contents:
        - pages_of_site/applied_project/welcome.qmd
format:
  html:
    theme: minty
    css: styles.css
    toc: true

editor: visual

