project:
  type: website
  output-dir: docs/

website:
  title: "Connie Ryan"
  search: false
  bread-crumbs: false
  navbar:
    left:
      - text: "Home"
        file: index.qmd
      - text: "Research"
        menu:
          - text: "Historical SDI & Contemporary Managment in CA"
            file: pages_of_site/applied_project.qmd
          - text: "Synthesis of Robust Historical SDI in CA & S. OR"
            file: pages_of_site/qq_data_project.qmd
          - text: "Fuel Treatment Spatial Patterns"
            file: pages_of_site/fuel_tx_spatial.qmd
      - file: about.qmd
format:
  html:
    theme: minty
    css: styles.css
    toc: true

editor: visual

